<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="tray_length" value="0.090"/>
    <xacro:property name="tray_radius" value="0.160"/>

    <xacro:macro name="cup_tray_element" params="tray_position">
        <link name="cup_tray">
            <visual>
                <geometry>
                    <cylinder length="${tray_length}" radius="${tray_radius}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 ${tray_length/2}" />
            </visual>

            <collision>
                <geometry>
                    <cylinder length="${tray_length}" radius="${tray_radius}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 ${tray_length/2}" />
            </collision>

            <inertial>
                <mass value="0.1"/>
                <origin rpy="0 0 0" xyz="0 0 ${tray_length/2}" />
                <inertia ixx="0.0007075" ixy="0" ixz="0" iyy="0.0007075" iyz="0" izz="0.00128"/>
            </inertial>
        </link>

        <joint name="cup_tray_chassis_link_joint" type="fixed">
            <origin rpy="0 0 0" xyz="${tray_position}" />
            <parent link="chassis" />
            <child link="cup_tray" />
        </joint>
    </xacro:macro> 
    
</robot>